{"text": "2022-01-15T16:14:42.544535+0100 ERROR Ciao (error)\n", "record": {"elapsed": {"repr": "0:00:56.078492", "seconds": 56.078492}, "exception": null, "extra": {}, "file": {"name": "server.py", "path": "/Users/ivansvitlychnyi/Desktop/Python Course/purilian-test/server.py"}, "function": "index", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 24, "message": "Ciao (error)", "module": "server", "name": "__main__", "process": {"id": 20061, "name": "MainProcess"}, "thread": {"id": 123145351577600, "name": "Thread-4"}, "time": {"repr": "2022-01-15 16:14:42.544535+01:00", "timestamp": 1642259682.544535}}}
